/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.dbms.jdbc.mysql.gui;

/**
 *
 * @author Jur Yel
 */
import java.util.ArrayList;
import java.util.Date;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import com.dbms.jdbc.mysql.core.IssuedBooks;
import com.dbms.jdbc.mysql.dao.IssuedBooksDAO;
import com.dbms.jdbc.mysql.dao.AccountsDAO;
import com.dbms.jdbc.mysql.dao.BooksDAO;
import javax.swing.JOptionPane;

public class IssuedBooksUI_Operations extends javax.swing.JDialog {

    /**
     * Creates new form IssuedBooksUI_Operations
     */
    private static final DateFormat sdf = new SimpleDateFormat("MM/dd/yyyy");
    
    private int userLevel;
    private String User_ID;
    private IssuedBooks issuedBook;
    private IssuedBooksDAO issuedDAO;
    private AccountsDAO accDAO;
    private BooksDAO bookDAO;
    private IssuedBooksUI issuedUI;
    private String operation;
    
    public IssuedBooksUI_Operations(String oprtn,int level, String userID, IssuedBooks issued, 
            IssuedBooksDAO dao, IssuedBooksUI ui){
        try{
            accDAO = new AccountsDAO();
            bookDAO = new BooksDAO();
        }
        catch(Exception exc){
            JOptionPane.showMessageDialog(IssuedBooksUI_Operations.this,"DAO Failed: "+ exc.getMessage(),"DAO Error",JOptionPane.ERROR_MESSAGE);
        }
        initComponents();
        setLocationRelativeTo(issuedUI);
        userLevel  = level;
        User_ID = userID;
        issuedBook = issued;
        issuedDAO = dao;
        issuedUI = ui;
        operation = oprtn;
        populateGUI(issuedBook);
        disableAll();
        if(operation.equalsIgnoreCase("renew")){
            setTitle("Renew Book");
            jbtn_Submit.setText("Renew Book");
        }
        else if(operation.equalsIgnoreCase("return")){
            setTitle("Return Book");
            jbtn_Submit.setText("Return Book");
        }
    }
    
    public IssuedBooksUI_Operations(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtxt_BookID = new javax.swing.JTextField();
        jtxt_Title = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtxt_UserID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jbtn_Submit = new javax.swing.JButton();
        jComboBox_DateBorrowed = new javax.swing.JComboBox<>();
        jComboBox_DateDue = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel1.setFont(new java.awt.Font("Josefin Sans", 0, 16)); // NOI18N
        jLabel1.setText("Book ID:");

        jtxt_BookID.setFont(new java.awt.Font("Josefin Sans", 0, 16)); // NOI18N
        jtxt_BookID.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jtxt_Title.setFont(new java.awt.Font("Josefin Sans", 0, 16)); // NOI18N
        jtxt_Title.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel2.setFont(new java.awt.Font("Josefin Sans", 0, 16)); // NOI18N
        jLabel2.setText("Book Title:");

        jtxt_UserID.setFont(new java.awt.Font("Josefin Sans", 0, 16)); // NOI18N
        jtxt_UserID.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel3.setFont(new java.awt.Font("Josefin Sans", 0, 16)); // NOI18N
        jLabel3.setText("User ID:");

        jLabel4.setFont(new java.awt.Font("Josefin Sans", 0, 16)); // NOI18N
        jLabel4.setText("Date Borrowed:");

        jLabel5.setFont(new java.awt.Font("Josefin Sans", 0, 16)); // NOI18N
        jLabel5.setText("Date Due:");

        jbtn_Submit.setBackground(new java.awt.Color(0, 0, 0));
        jbtn_Submit.setFont(new java.awt.Font("Josefin Sans", 0, 16)); // NOI18N
        jbtn_Submit.setForeground(new java.awt.Color(255, 255, 255));
        jbtn_Submit.setText("Renew Book");
        jbtn_Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_SubmitActionPerformed(evt);
            }
        });

        jComboBox_DateBorrowed.setFont(new java.awt.Font("Josefin Sans", 0, 16)); // NOI18N

        jComboBox_DateDue.setFont(new java.awt.Font("Josefin Sans", 0, 16)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtxt_UserID)
                            .addComponent(jtxt_Title)
                            .addComponent(jtxt_BookID, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                            .addComponent(jComboBox_DateBorrowed, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBox_DateDue, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(jbtn_Submit)))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtxt_BookID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtxt_Title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtxt_UserID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBox_DateBorrowed, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jComboBox_DateDue, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21)
                .addComponent(jbtn_Submit, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtn_SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_SubmitActionPerformed
        if(operation.equalsIgnoreCase("renew")){
            renewBook();
        }
        else if(operation.equalsIgnoreCase("return")){
            returnBook();
        }
    }//GEN-LAST:event_jbtn_SubmitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IssuedBooksUI_Operations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IssuedBooksUI_Operations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IssuedBooksUI_Operations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IssuedBooksUI_Operations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                IssuedBooksUI_Operations dialog = new IssuedBooksUI_Operations(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox_DateBorrowed;
    private javax.swing.JComboBox<String> jComboBox_DateDue;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbtn_Submit;
    private javax.swing.JTextField jtxt_BookID;
    private javax.swing.JTextField jtxt_Title;
    private javax.swing.JTextField jtxt_UserID;
    // End of variables declaration//GEN-END:variables

    private void returnBook(){
        String userID = jtxt_UserID.getText();
        String bookID = jtxt_BookID.getText();
        try{
            int quantity = bookDAO.getBookQuantity(bookID);
            issuedDAO.returnBook(User_ID,userID, bookID,quantity);
            issuedUI.refreshIssuedBooks();
            setVisible(false);
            JOptionPane.showMessageDialog(issuedUI,"Book returned successfully!","Return Success",JOptionPane.INFORMATION_MESSAGE);
        }
        catch(Exception exc){
            JOptionPane.showMessageDialog(IssuedBooksUI_Operations.this,"Return Failed: "+exc.getMessage(),"Return Error",JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void renewBook(){
        String bookID = jtxt_BookID.getText();
        String userID = jtxt_UserID.getText();
        Date brwd = issuedBook.getDateBorrowed();
        Date due = issuedBook.getDateDue();
        Date curDay = new Date();
        
        int brwdDay = brwd.getDate();
        int dueDay = due.getDate();
        try{
            if(accDAO.checkIfBlocked(userID)){
                setVisible(false);
                JOptionPane.showMessageDialog(issuedUI,"Unable to renew book, account is blocked!","Renewal Error",JOptionPane.ERROR_MESSAGE);
            }
            else{
                if((dueDay - curDay.getDate()) != 0){
                    setVisible(false);
                    JOptionPane.showMessageDialog(issuedUI,"Renewal is only allowed on due date","Renewal Error",JOptionPane.ERROR_MESSAGE);
                }
                else{

                        String title = issuedDAO.getBookTitleByUserID(bookID);
                        IssuedBooks issued = new IssuedBooks(bookID,title,userID,brwd,due);
                        issuedDAO.renewBook(issued,User_ID);
                        issuedUI.refreshIssuedBooks();
                        setVisible(false);
                        JOptionPane.showMessageDialog(issuedUI,"Book renewed successfully!","Renewal Success",JOptionPane.INFORMATION_MESSAGE);

                }
            }
            
        }
        catch(Exception exc){
            JOptionPane.showMessageDialog(IssuedBooksUI_Operations.this,"Renewal Failed: "+exc.getMessage(),"Renewal Error",JOptionPane.ERROR_MESSAGE);
        }
            
        
        
    }
    
    private void populateGUI(IssuedBooks issued){
        jtxt_BookID.setText(issued.getBookID());
        jtxt_Title.setText(issued.getBookTitle());
        jtxt_UserID.setText(issued.getUserID());
        jComboBox_DateBorrowed.addItem(sdf.format(issued.getDateBorrowed()));
        jComboBox_DateDue.addItem(sdf.format(issued.getDateDue()));
    }
    
    private void disableAll(){
        jtxt_BookID.setEnabled(false);
        jtxt_Title.setEnabled(false);
        jtxt_UserID.setEnabled(false);
        jComboBox_DateBorrowed.setEnabled(false);
        jComboBox_DateDue.setEnabled(false);
    }
}
