/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.dbms.jdbc.mysql.gui;

/**
 *
 * @author Jur Yel
 */
import java.util.ArrayList;
import com.dbms.jdbc.mysql.core.IssuedBooks;
import com.dbms.jdbc.mysql.dao.IssuedBooksDAO;
import com.dbms.jdbc.mysql.gui.history.TransactionsUI;
import com.dbms.jdbc.mysql.gui.history.OverduedBooksUI;
import com.dbms.jdbc.mysql.gui.history.ReturnedBooksUI;
import java.util.Date;
import javax.swing.JOptionPane;

public class IssuedBooksUI extends javax.swing.JFrame {

    /**
     * Creates new form IssuedBooksUI
     */
    private IssuedBooksDAO issuedDAO;
    private String User_ID;
    private String UserName;
    private int userLevel;
    
    public IssuedBooksUI(int level, String userID,String userName){
        try{
            issuedDAO = new IssuedBooksDAO();
            issuedDAO.overduedBooks();
        }
        catch(Exception exc){
            JOptionPane.showMessageDialog(IssuedBooksUI.this,"DAO Failed: "+exc.getMessage(),"DAO Error",JOptionPane.ERROR_MESSAGE);
        }
        initComponents();
        setLocationRelativeTo(null);
        userLevel = level;
        User_ID = userID;
        UserName = userName;
        populateTable();
        switch(userLevel){
            case 0:
                jlbl_Label.setText("Admin: ");
                jlbl_Online.setText(UserName);
                break;
            case 1:
                jlbl_Label.setText("Asst: ");
                jlbl_Online.setText(UserName);
                break;
            case 2:
                jlbl_Label.setText("Online: ");
                jlbl_Online.setText(UserName);
                break;          
        }
        checkOverduedBooks();
        
    }
    
    public IssuedBooksUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jlbl_Label = new javax.swing.JLabel();
        jlbl_Online = new javax.swing.JLabel();
        jtxt_Search = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbl_IssuedBooks = new javax.swing.JTable();
        jbtn_Return = new javax.swing.JButton();
        jbtn_Renew = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LBMS: Issued Books");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jlbl_Label.setFont(new java.awt.Font("Josefin Sans", 0, 14)); // NOI18N
        jlbl_Label.setText("Online:");

        jlbl_Online.setFont(new java.awt.Font("Josefin Sans", 0, 14)); // NOI18N
        jlbl_Online.setText("jLabel1");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbl_Label)
                .addGap(18, 18, 18)
                .addComponent(jlbl_Online)
                .addContainerGap(77, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbl_Label)
                    .addComponent(jlbl_Online))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jtxt_Search.setFont(new java.awt.Font("Josefin Sans", 0, 16)); // NOI18N
        jtxt_Search.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxt_Search.setText("Search Issued Book...");
        jtxt_Search.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jtxt_Search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jtxt_SearchMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jtxt_SearchMouseExited(evt);
            }
        });
        jtxt_Search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxt_SearchKeyTyped(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jtbl_IssuedBooks.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtbl_IssuedBooks);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 773, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 377, Short.MAX_VALUE)
        );

        jbtn_Return.setBackground(new java.awt.Color(0, 0, 0));
        jbtn_Return.setFont(new java.awt.Font("Josefin Sans", 0, 16)); // NOI18N
        jbtn_Return.setForeground(new java.awt.Color(255, 255, 255));
        jbtn_Return.setText("Return Book");
        jbtn_Return.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_ReturnActionPerformed(evt);
            }
        });

        jbtn_Renew.setBackground(new java.awt.Color(0, 0, 0));
        jbtn_Renew.setFont(new java.awt.Font("Josefin Sans", 0, 16)); // NOI18N
        jbtn_Renew.setForeground(new java.awt.Color(255, 255, 255));
        jbtn_Renew.setText("Renew Book");
        jbtn_Renew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_RenewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(190, 190, 190)
                .addComponent(jbtn_Renew)
                .addGap(158, 158, 158)
                .addComponent(jbtn_Return)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jtxt_Search, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(271, 271, 271))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtxt_Search, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtn_Renew, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn_Return, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jMenuBar1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jMenu1.setText("File");

        jMenuItem1.setText("Logout");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);
        jMenu1.add(jSeparator1);

        jMenuItem2.setText("Exit");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("View");

        jMenuItem3.setText("Accounts");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuItem4.setText("Book Records");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("History");

        jMenuItem5.setText("Transactions");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem5);
        jMenu3.add(jSeparator2);

        jMenuItem6.setText("Overdued Books");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem6);

        jMenuItem7.setText("Returned Books");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem7);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxt_SearchKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxt_SearchKeyTyped
       String key = jtxt_Search.getText().trim();
       
       try{
          if(key.isEmpty()){
            ArrayList<IssuedBooks> list = issuedDAO.getAllIssuedBooks();
            IssuedBooksTableModel model = new IssuedBooksTableModel(list);
            jtbl_IssuedBooks.setModel(model);
            } 
          else{
              ArrayList<IssuedBooks> list = issuedDAO.searchIssuedBook(key);
              IssuedBooksTableModel model = new IssuedBooksTableModel(list);
              jtbl_IssuedBooks.setModel(model);
          }
       }
       catch(Exception exc){
           JOptionPane.showMessageDialog(IssuedBooksUI.this,"Search Failed: "+exc.getMessage(),"Search Error",JOptionPane.ERROR_MESSAGE);
       }
       
    }//GEN-LAST:event_jtxt_SearchKeyTyped

    private void jbtn_RenewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_RenewActionPerformed
        int row = jtbl_IssuedBooks.getSelectedRow();
        if(row < 0){
            JOptionPane.showMessageDialog(IssuedBooksUI.this,"Select a row","Renew Error",JOptionPane.ERROR_MESSAGE);
        }
        else{
            String bookID = jtbl_IssuedBooks.getValueAt(row,0).toString();
            String bookTitle = jtbl_IssuedBooks.getValueAt(row,1).toString();
            String userID = jtbl_IssuedBooks.getValueAt(row,2).toString();
            Date dateBrwd = (Date)jtbl_IssuedBooks.getValueAt(row,3);
            Date datedue = (Date)jtbl_IssuedBooks.getValueAt(row,4);
            
            IssuedBooks issuedBook = new IssuedBooks(bookID,bookTitle,userID,dateBrwd,datedue);
            IssuedBooksUI_Operations renew = new IssuedBooksUI_Operations("renew",userLevel,User_ID,
                    issuedBook,issuedDAO,IssuedBooksUI.this);
            renew.setVisible(true);
        }
    }//GEN-LAST:event_jbtn_RenewActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        AccountsUI accountUI = new AccountsUI(userLevel,User_ID,UserName);
        setVisible(false);
        accountUI.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        BooksUI bookUI = new BooksUI(userLevel,User_ID,UserName);
        setVisible(false);
        bookUI.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        Main_LoginUI login = new Main_LoginUI();
        setVisible(false);
        login.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        dispose();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jbtn_ReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_ReturnActionPerformed
        int row = jtbl_IssuedBooks.getSelectedRow();
        if(row < 0){
            JOptionPane.showMessageDialog(IssuedBooksUI.this, "Select a row","Return Error",JOptionPane.ERROR_MESSAGE);
        }
        else{
            String bookID = jtbl_IssuedBooks.getValueAt(row,0).toString();
            String bookTitle = jtbl_IssuedBooks.getValueAt(row,1).toString();
            String userID = jtbl_IssuedBooks.getValueAt(row,2).toString();
            Date dateBrwd = (Date)jtbl_IssuedBooks.getValueAt(row,3);
            Date datedue = (Date)jtbl_IssuedBooks.getValueAt(row,4);
            
            IssuedBooks issuedBook = new IssuedBooks(bookID,bookTitle,userID,dateBrwd,datedue);
            IssuedBooksUI_Operations returnBook = new IssuedBooksUI_Operations("return",
                    userLevel,User_ID,issuedBook,issuedDAO,IssuedBooksUI.this);
            returnBook.setVisible(true);
        }
    }//GEN-LAST:event_jbtn_ReturnActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        TransactionsUI trans = new TransactionsUI(userLevel,User_ID,UserName);
        setVisible(false);
        trans.setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        OverduedBooksUI overdued = new OverduedBooksUI(userLevel,UserName,IssuedBooksUI.this);
        setVisible(false);
        overdued.setVisible(true);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        ReturnedBooksUI returnUI = new ReturnedBooksUI(userLevel,UserName,IssuedBooksUI.this);
        setVisible(false);
        returnUI.setVisible(true);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jtxt_SearchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxt_SearchMouseEntered
        if(jtxt_Search.getText().contains("Search Issued Book...")){
            jtxt_Search.setText("");
        }
    }//GEN-LAST:event_jtxt_SearchMouseEntered

    private void jtxt_SearchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxt_SearchMouseExited
       if(jtxt_Search.getText().isEmpty()){
           jtxt_Search.setText("Search Issued Book...");
       }
    }//GEN-LAST:event_jtxt_SearchMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IssuedBooksUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IssuedBooksUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IssuedBooksUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IssuedBooksUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IssuedBooksUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JButton jbtn_Renew;
    private javax.swing.JButton jbtn_Return;
    private javax.swing.JLabel jlbl_Label;
    private javax.swing.JLabel jlbl_Online;
    private javax.swing.JTable jtbl_IssuedBooks;
    private javax.swing.JTextField jtxt_Search;
    // End of variables declaration//GEN-END:variables

    
    
    public void refreshIssuedBooks(){
        try{
            ArrayList<IssuedBooks> list = issuedDAO.getAllIssuedBooks();
            IssuedBooksTableModel model = new IssuedBooksTableModel(list);
            jtbl_IssuedBooks.setModel(model);
        }
        catch(Exception exc){
            JOptionPane.showMessageDialog(IssuedBooksUI.this,"Refresh Failed: "+exc.getMessage(),"Refresh Error",JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void populateTable(){
        try{
            ArrayList<IssuedBooks> list = issuedDAO.getAllIssuedBooks();
            IssuedBooksTableModel model = new IssuedBooksTableModel(list);
            jtbl_IssuedBooks.setModel(model);
        }
        catch(Exception exc){
            JOptionPane.showMessageDialog(IssuedBooksUI.this, "Load Failed: "+exc.getMessage(),"Load Error",JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void checkOverduedBooks(){
        try{
            ArrayList<IssuedBooks> list = issuedDAO.getAllIssuedBooks();
            int count = 0;
            for(int i = 0;i<list.size();i++){
                if(issuedDAO.checkIfOverdued(list.get(i).getUserID(), list.get(i).getBookID())){
                    count++;
                }
            }
            if(count != 0){
                
                String str = String.format("%s",(count > 1)? "books are" : "book is");
                JOptionPane.showMessageDialog(IssuedBooksUI.this,
                        "As of this date, " + count + " " + str + " overdued",
                        "Books Overdued",JOptionPane.INFORMATION_MESSAGE);
            }
        
        }
        catch(Exception exc){
            JOptionPane.showMessageDialog(IssuedBooksUI.this,"Check Failed: "+exc.getMessage(),"Check Error",JOptionPane.ERROR_MESSAGE);
        }
    }
}
