/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.dbms.jdbc.mysql.gui;

/**
 *
 * @author Jur Yel
 */
import com.dbms.jdbc.mysql.dao.AccountsDAO;
import com.dbms.jdbc.mysql.core.Accounts;
import javax.swing.JOptionPane;
public class Main_RegisterUI extends javax.swing.JFrame {

    /**
     * Creates new form Main_RegisterUI
     */
    private AccountsDAO accDAO;
    public Main_RegisterUI() {
        try{
            accDAO = new AccountsDAO();
        }
        catch(Exception exc){
            JOptionPane.showMessageDialog(Main_RegisterUI.this, "DAO Failed: "+exc.getMessage(),"DAO Error",JOptionPane.ERROR_MESSAGE);
        }
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jtxt_UserID = new javax.swing.JTextField();
        jtxt_FirstName = new javax.swing.JTextField();
        jpf_Password = new javax.swing.JPasswordField();
        jtxt_LastName = new javax.swing.JTextField();
        jComboBox_Position = new javax.swing.JComboBox<>();
        jbtn_Register = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LBMS: Register");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jtxt_UserID.setFont(new java.awt.Font("Josefin Sans", 0, 16)); // NOI18N
        jtxt_UserID.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxt_UserID.setText("User ID");
        jtxt_UserID.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jtxt_UserID.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jtxt_UserIDMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jtxt_UserIDMouseExited(evt);
            }
        });
        jtxt_UserID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_UserIDActionPerformed(evt);
            }
        });

        jtxt_FirstName.setFont(new java.awt.Font("Josefin Sans", 0, 16)); // NOI18N
        jtxt_FirstName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxt_FirstName.setText("First Name");
        jtxt_FirstName.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jtxt_FirstName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jtxt_FirstNameMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jtxt_FirstNameMouseExited(evt);
            }
        });

        jpf_Password.setFont(new java.awt.Font("Josefin Sans", 0, 16)); // NOI18N
        jpf_Password.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jpf_Password.setText("Password");
        jpf_Password.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jpf_Password.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jpf_PasswordMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jpf_PasswordMouseExited(evt);
            }
        });
        jpf_Password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jpf_PasswordKeyTyped(evt);
            }
        });

        jtxt_LastName.setFont(new java.awt.Font("Josefin Sans", 0, 16)); // NOI18N
        jtxt_LastName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxt_LastName.setText("Last Name");
        jtxt_LastName.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jtxt_LastName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jtxt_LastNameMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jtxt_LastNameMouseExited(evt);
            }
        });

        jComboBox_Position.setFont(new java.awt.Font("Josefin Sans", 0, 16)); // NOI18N
        jComboBox_Position.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Student" }));
        jComboBox_Position.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addComponent(jComboBox_Position, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(118, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(14, 14, 14)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jtxt_FirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jtxt_LastName, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jtxt_UserID, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jpf_Password, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(14, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(120, Short.MAX_VALUE)
                .addComponent(jComboBox_Position, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(12, 12, 12)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtxt_UserID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jpf_Password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtxt_FirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jtxt_LastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(65, Short.MAX_VALUE)))
        );

        jbtn_Register.setBackground(new java.awt.Color(0, 0, 0));
        jbtn_Register.setFont(new java.awt.Font("Josefin Sans", 0, 16)); // NOI18N
        jbtn_Register.setForeground(new java.awt.Color(255, 255, 255));
        jbtn_Register.setText("Register");
        jbtn_Register.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtn_Register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_RegisterActionPerformed(evt);
            }
        });

        jCheckBox1.setFont(new java.awt.Font("Josefin Sans", 0, 13)); // NOI18N
        jCheckBox1.setText("Show Password");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Josefin Sans", 2, 13)); // NOI18N
        jLabel1.setText("Already have an account?");

        jLabel2.setFont(new java.awt.Font("Josefin Sans", 0, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 255));
        jLabel2.setText("Login");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Coolvetica Rg", 0, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 255));
        jLabel4.setText("Management System");

        jLabel3.setFont(new java.awt.Font("Coolvetica Rg", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 255));
        jLabel3.setText("Library");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox1)
                    .addComponent(jbtn_Register, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(204, 204, 204))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(107, 107, 107)
                                .addComponent(jLabel3)))))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jCheckBox1)
                .addGap(20, 20, 20)
                .addComponent(jbtn_Register, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxt_UserIDMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxt_UserIDMouseEntered
        if(jtxt_UserID.getText().contains("User ID")){
            jtxt_UserID.setText("");
        }
    }//GEN-LAST:event_jtxt_UserIDMouseEntered

    private void jtxt_UserIDMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxt_UserIDMouseExited
        if(jtxt_UserID.getText().isEmpty()){
            jtxt_UserID.setText("User ID");
        }
    }//GEN-LAST:event_jtxt_UserIDMouseExited

    private void jtxt_FirstNameMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxt_FirstNameMouseEntered
        if(jtxt_FirstName.getText().contains("First Name")){
            jtxt_FirstName.setText("");
        }
    }//GEN-LAST:event_jtxt_FirstNameMouseEntered

    private void jtxt_LastNameMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxt_LastNameMouseEntered
        if(jtxt_LastName.getText().contains("Last Name")){
            jtxt_LastName.setText("");
        }
    }//GEN-LAST:event_jtxt_LastNameMouseEntered

    private void jtxt_FirstNameMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxt_FirstNameMouseExited
       if(jtxt_FirstName.getText().isEmpty()){
           jtxt_FirstName.setText("First Name");
       }
    }//GEN-LAST:event_jtxt_FirstNameMouseExited

    private void jtxt_LastNameMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxt_LastNameMouseExited
        if(jtxt_LastName.getText().isEmpty()){
            jtxt_LastName.setText("Last Name");
        }
    }//GEN-LAST:event_jtxt_LastNameMouseExited

    private void jpf_PasswordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpf_PasswordMouseEntered
        if(jpf_Password.getText().contains("Password")){
            jpf_Password.setText("");
        }
    }//GEN-LAST:event_jpf_PasswordMouseEntered

    private void jpf_PasswordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpf_PasswordMouseExited
        if(jpf_Password.getText().isEmpty()){
            jpf_Password.setEchoChar((char)0);
            jpf_Password.setText("Password");
        }
    }//GEN-LAST:event_jpf_PasswordMouseExited

    private void jpf_PasswordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jpf_PasswordKeyTyped
        jpf_Password.setEchoChar('*');
    }//GEN-LAST:event_jpf_PasswordKeyTyped

    private void jtxt_UserIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_UserIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_UserIDActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        if(jCheckBox1.isSelected()){
            jpf_Password.setEchoChar((char)0);
        }
        else{
            jpf_Password.setEchoChar('*');
        }
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jbtn_RegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_RegisterActionPerformed
        String userID = jtxt_UserID.getText().trim();
        String pass = jpf_Password.getText().trim();
        String first = jtxt_FirstName.getText().trim();
        String last = jtxt_LastName.getText().trim();
        String position = jComboBox_Position.getSelectedItem().toString();
        
        try{
            if(userID.equals("User ID") || pass.equals("Password") || first.equals("First Name") || last.equals("Last Name")){
                JOptionPane.showMessageDialog(Main_RegisterUI.this,"Fill in all fields","Registration Error",JOptionPane.ERROR_MESSAGE);
            }
            else{
                if(accDAO.checkIfExist(userID)){
                    JOptionPane.showMessageDialog(Main_RegisterUI.this, "User ID already exists!","Registration Error",JOptionPane.ERROR_MESSAGE);
                }
                else{
                    if(userID.length() < 11){
                        JOptionPane.showMessageDialog(Main_RegisterUI.this, "User ID must be 11 digits long");
                    }
                    else{
                        Accounts account = new Accounts(userID,last,first,pass,position,false);
                        accDAO.RegisterAccount(account);
                        JOptionPane.showMessageDialog(Main_RegisterUI.this, "Registration Successful!","Success",JOptionPane.INFORMATION_MESSAGE);
                        Main_LoginUI login = new Main_LoginUI();
                        this.setVisible(false);
                        reset();
                        login.setVisible(true);
                    }
                    
                    
                }
            }
        }
        catch(Exception exc){
            JOptionPane.showMessageDialog(Main_RegisterUI.this,"Registration Failed: "+exc.getMessage(),"Registration Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jbtn_RegisterActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        Main_LoginUI login = new Main_LoginUI();
        this.setVisible(false);
        login.setVisible(true);
        
    }//GEN-LAST:event_jLabel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main_RegisterUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main_RegisterUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main_RegisterUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main_RegisterUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main_RegisterUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JComboBox<String> jComboBox_Position;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton jbtn_Register;
    private javax.swing.JPasswordField jpf_Password;
    private javax.swing.JTextField jtxt_FirstName;
    private javax.swing.JTextField jtxt_LastName;
    private javax.swing.JTextField jtxt_UserID;
    // End of variables declaration//GEN-END:variables

    public void reset(){
        jtxt_UserID.setText("User ID");
        jpf_Password.setText("Password");
        jtxt_FirstName.setText("First Name");
        jtxt_LastName.setText("Last Name");
    }
}
